<div id="answers_container">
<?php if( !$answers ): ?>
<?php else: ?>
    <div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('poll')->__('Uploaded Hairstyles') ?></h4>
    </div>
    <?php foreach($answers->getItems() as $_item): ?>
        <div class="fieldset fieldset-wide" id="poll_answer_fieldset_<?php echo $_item->getId() ?>"<?php echo stripos($_item->getAnswerTitle(),'dummy item only') !== FALSE?' style="display:none"':''; ?>>
        <table cellspacing="0" class="form-list">
            <?php if(Mage::registry('poll_data')->getPollType() == 1 || Mage::getSingleton('core/session')->getThePollType()==1):?>
            <input type="hidden" id="answer_<?php echo $_item->getId() ?>" name="answer[<?php echo $_item->getId() ?>][title]" value="<?php echo $this->escapeHtml($_item->getAnswerTitle()) ?>" class="input-text required-entry" />
            <?php else:?>
            <tr>
                <td class="label"><label for="answer_<?php echo $_item->getId() ?>"><?php echo Mage::helper('poll')->__('Answer Title:') ?> <span class="required">*</span></label></td>
                <td class="value"><input type="text" id="answer_<?php echo $_item->getId() ?>" name="answer[<?php echo $_item->getId() ?>][title]" value="<?php echo $this->escapeHtml($_item->getAnswerTitle()) ?>" class="input-text required-entry" /></td>
            </tr>
            <?php endif; ?>
            <?php if(Mage::registry('poll_data')->getPollType() == 1 || Mage::getSingleton('core/session')->getThePollType()==1 ):?>
            <tr>
            	<td colspan="2">
                	<img style="height:150px;width:auto" src="/media/vote-assistant/<?php echo $_item->getPollId(); ?>/<?php echo $_item->getAnswerTitle(); ?>">
					<?php
                        if($_item->getCid() > 10000){
                            $the_id = $_item->getCid() - 10000;
                            /*$id = 2;
                            $role_data = Mage::getModel('admin/user')->load($id)->getRole()->getData();
                            var_dump($role_data);
                            $username = 'admin';
                            $role_data = Mage::getModel('admin/user')->getCollection()->addFieldToFilter('username',$username)->getFirstItem()->getRole()->getData();
                            var_dump($role_data);*/
                            $customer = Mage::getModel('admin/user')->load($the_id);
                        }else{
                            $customer = Mage::getModel('customer/customer')->load($_item->getCid());
                        }
						//echo $customer->getEmail();
                    ?>
                    <div>
                    	Uploaded By: <?php echo $customer->getFirstname() . ' '. $customer->Lastname;?> (<?php echo $customer->getEmail(); ?>)
                    </div>
                </td>
            </tr>
            <?php endif; ?>
            <?php if(Mage::registry('poll_data')->getPollType() == 1 || Mage::getSingleton('core/session')->getThePollType()==1 ):?>
            <tr>
                <td class="label"><label for="answer_status_<?php echo $_item->getId() ?>"><?php echo Mage::helper('poll')->__('Status:') ?> <span class="required">*</span></label></td>
                <td class="value">
                <select id="answer_status_<?php echo $_item->getId() ?>" name="answer[<?php echo $_item->getId() ?>][status]">
                	<option value="0" <?php echo $this->escapeHtml($_item->getAnswerStatus()==0)?'selected="selected"':'' ?>>Pending</option>
                	<option value="1" <?php echo $this->escapeHtml($_item->getAnswerStatus()==1)?'selected="selected"':'' ?>>Approved</option>
                </select>
                </td>
            </tr>
            <?php else:?>
                <input type="hidden" id="answer_status_<?php echo $_item->getId() ?>" name="answer[<?php echo $_item->getId() ?>][status]" value="0">
            <?php endif; ?>
            <tr>
                <td class="label"><label for="answer_votes_<?php echo $_item->getId() ?>"><?php echo Mage::helper('poll')->__('Votes Count:') ?> <span class="required">*</span></label></td>
                <td class="value"><input type="text" id="answer_votes_<?php echo $_item->getId() ?>" name="answer[<?php echo $_item->getId() ?>][votes]" value="<?php echo $_item->getVotesCount() ?>" class="input-text required-entry validate-not-negative-number" />
                    <p class="a-left" style="margin:7px 0 0;"><?php echo $this->getDeleteButtonHtml() ?></p>
                </td>
             </tr>
        </table>
        <input type="hidden" id="id_poll_answer_fieldset_<?php echo $_item->getId() ?>" value="<?php echo $_item->getId() ?>" />
        </div>
    <?php endforeach; ?>
<?php endif; ?>
</div>
<?php 
if(Mage::registry('poll_data')->getPollType() == 1 || Mage::getSingleton('core/session')->getThePollType()==1 ):
$user = Mage::getSingleton('admin/session'); 
$userId = $user->getUser()->getUserId()+10000;
?>
   <div id="image-uploader-container" class="sw" style="display:block;margin-top:50px;">
        <div id="image-uploader" class="sw">
            <form action="<?php echo Mage::getUrl('vote/index/save') ?>" method="post" enctype="multipart/form-data">
                <input type="hidden" name="poll_id" value="<?php echo $the_poll_id;?>">
                <input type="hidden" name="scrolltop" value="0">
                <input type="hidden" name="cid" value="<?php echo $userId; ?>">
                <input type="file" id="bs_image" name="bs_image" required="true"/>
                <div id="btn-upload" class="button-container"><input class="button" type="submit" value="Upload Hairstyle Image" style="padding:10px 20px;margin-top:15px"></div>
            </form>
        </div>
    </div>;
<?php else:?>
<p class="a-right" style="margin:7px 0 0;"><?php echo $this->getAddButtonHtml(); ?></p>
<?php endif; ?>
<script type="text/javascript">
//<![CDATA[
    var lastId = 0;
    var answer = function() {
        return {
            del : function(obj) {
                if( confirm('<?php echo Mage::helper('core')->jsQuoteEscape(Mage::helper('poll')->__('Are you sure you want to delete it?')) ?>') ) {
                    fieldSet = obj.up('div.fieldset');
                    if( $('id_' + fieldSet.id) ) {
                        var itemId = $('id_' + fieldSet.id).value;
                        var newElement = document.createElement('input');
                        newElement.type = 'hidden';
                        newElement.value = itemId;
                        newElement.name = 'deleteAnswer[]';
                        $('answers_container').appendChild(newElement);
                    }
                    fieldSet.remove();
                }
            },

            add : function(obj) {
                var newElement = document.createElement('div');
                newElement.innerHTML = this.getTemplate();
                $('answers_container').appendChild(newElement);
            },
            <?php if(Mage::registry('poll_data')->getPollType() == 1 || Mage::getSingleton('core/session')->getThePollType()==1 ):?>
			<?php else: ?>
            getTemplate : function() {
                var id = this.createId();
                return  '<div class="fieldset fieldset-wide" id="poll_answer_fieldset_' + id + '">'
                       +'<table cellspacing="0" class="form-list">'
                       +'<tr>'
                       +    '<td class="label"><label for="answer_' + id + '"><?php echo Mage::helper('core')->jsQuoteEscape(Mage::helper('poll')->__('Answer Title:')) ?> <span class="required">*</span></label><\/td>'
                       +    '<td class="value"><input type="text" id="answer_' + id + '" name="answer[' + id + '][title]" value="" class="input-text required-entry" /><\/td>'
                       +'<\/tr>'
            /*+'<tr>'
            +'    <td class="label"><label for="answer_status_'+id+'"><?php echo Mage::helper('core')->jsQuoteEscape(Mage::helper('poll')->__('Status:')) ?> <span class="required">*</span></label></td>'
            +'    <td class="value">'
            +'    <select id="answer_status_'+id+'" name="answer[' + id + '][status]">'
            +'    	<option value="0">Pending</option>'
            +'    	<option value="1">Approved</option>'
            +'    </select>'
            +'    </td>'
            +'<\/tr>'*/
            +'    <input type="hidden" id="answer_status_'+id+'" name="answer[' + id + '][status]" value="0">'
                       +'<tr>'
                       +    '<td class="label"><label for="answer_votes_' + id + '"><?php echo Mage::helper('core')->jsQuoteEscape(Mage::helper('poll')->__('Votes Count:')) ?> <span class="required">*</span></label><\/td>'
                       +    '<td class="value"><input type="text" id="answer_votes_' + id + '" name="answer[' + id + '][votes]" value="0" class="input-text required-entry validate-not-negative-number" />'
                       +        '<p class="a-left" style="margin:7px 0 0;"><?php echo Mage::helper('core')->quoteEscape($this->getDeleteButtonHtml()) ?></p>'
                       +'<\/td>'
                       +'<\/tr>'
                       +'<\/table>'
                       +'<input type="hidden" id="id_poll_answer_fieldset_' + id + '" value="' + id + '" />'
                       +'<\/div>';
            },


			<?php endif;?>

            createId : function () {
                return --lastId;
            }
        }
    }();
//]]>
</script>
