<?php $_helper = Mage::helper('catalog/category');?>
<?php $_categories = $_helper->getStoreCategories(false, true, false);?>
<?php $_categories->addAttributeToSelect('image');?>
<?php $_categories->addAttributeToSelect('description');?>
<?php 
$i = 0;
if (count($_categories) > 0): 
?>
	<div class="category-nav">
    	<div class="category-nav-inner">
<?php
	foreach($_categories as $_category):
				$path = $_category->getPath();
				$ids = explode('/', $path);
				if (count($ids) > 3){
					//$topParent = Mage::getModel('catalog/category')->setStoreId(Mage::app()->getStore()->getId())->load($ids[2]);
					$topParent = TRUE;
				}
				else{
					$topParent = FALSE;//it means you are in one catalog root.
				}
				if($topParent === TRUE){
					continue;
				}
?>
            <a href="<?php echo $_helper->getCategoryUrl($_category) ?>"><?php echo $_category->getName(); ?></a>
<?php	 
	endforeach;
?>
        </div>
    </div>
    <div class="vh-shop-home" style="clear:both;">
        <?php foreach($_categories as $_category):
				$path = $_category->getPath();
				$ids = explode('/', $path);
				if (count($ids) > 3){
					//$topParent = Mage::getModel('catalog/category')->setStoreId(Mage::app()->getStore()->getId())->load($ids[2]);
					$topParent = TRUE;
				}
				else{
					$topParent = FALSE;//it means you are in one catalog root.
				}
				if($topParent === TRUE){
					continue;
				}
		?> 
        	<div class="category-item clearer">
            	<div class="the-category-image">
                    <a href="<?php echo $_helper->getCategoryUrl($_category) ?>">
                <?php
                    $_imgHtml   = '';
                    if ($_imgUrl = $_category->getImageUrl()) {
                        $_imgHtml = '<img src="'.$_imgUrl.'" alt="'.$this->escapeHtml($_category->getName()).'" title="'.$this->escapeHtml($_category->getName()).'" />';
                    }
                    echo $_imgHtml;
                ?>
                    </a>
                </div>
            	<div class="the-category-description">
                    <h3 class="top-h">SHOP</h3>
                    <h3><a href="<?php echo $_helper->getCategoryUrl($_category) ?>"><?php echo $_category->getName() ?></a></h3>
                    <div class="cat-desc"><?php echo $_category->getDescription() ?></div>
                    <div class="more-link"><a href="<?php echo $_helper->getCategoryUrl($_category) ?>" class="more">Shop Now <i class="fa fa-angle-right"></i></a></div>
                </div>
            </div>
		<?php endforeach;?>
    </div>
<?php endif; ?>