<style>
	.page-title{
		margin-bottom:0px;
	}
	.page-title h1{
		color:#2D2B28;
		font-size:34px;
		text-align:center;
		max-width:700px;
		margin:0 auto;
	}
	.video-intro p,
	.video-intro{
		color:#a7a7a7;
		font-size:16px;
		text-align:center;
		max-width:700px;
		line-height:26px;
		margin:0 auto;
	}
	.the-videos > div{
		margin-left:-20px;
	}
	.the-videos > div > div.video{
		margin-top:60px;
		padding-left:20px;
		width:50%;
		box-sizing:border-box;
		text-align:center;
		float:left;
	}
	h3.video-title{
		margin:0;
	}
	h3.video-title a.video-link2{
		color:#404040;
		letter-spacing:1px;
		margin:20px auto 0px auto;
		font-size:16px;
		display:inline-block;
		max-width:400px;
	}
	div.video-description{
		color:#808285;
		font-size:14px;
		margin:0 auto;
		max-width:400px;
	}
	.the-videos{
		margin-bottom:70px;
	}
	.video .video-link, .product-video .video-link{
		background:none;
	}
	.review-links{
		text-align:center;
		margin-bottom:15px;
	}
	.review-links .review-link{
		display:inline-block;
		width:200px;
		height:35px;
		text-align:center;
		line-height:35px;
		border:1px solid #dbdbdb;
		font-size:16px;
	}
	.review-links a.review-link{
		background:#fff;
		color:#59595b;
	}
	.review-links span.review-link{
		background:#6d6e70;
		color:#fff;
	}
	.video-review .video-description{
		margin-top:60px;
	}
	.video-intro img{
		display:inline-block;
	}
	.video-intro{
		text-align:center;
		margin-top:30px;
	}
	.the-review-item{
		margin:20px auto 0 auto;
		border-bottom:1px solid;
		text-align:center;
		max-width:900px;
		padding:0 30px 20px 30px;
	}
	.the-review-item:last{
		margin-bottom:60px;
	}
	.the-reviewer{
		text-align:center;
		font-family:"Times New Roman", Times, serif;
		font-style:italic;
		margin-top:10px;
	}
	.video-intro{
		width:100%;
	}
	.video-intro img{
		width:100%;
		max-width:500px;
		height:auto;
	}
</style>
<div class="container" style="text-align:center;margin-top:80px">
	<div class="review-links">
    	<div>
        	<a style="margin-right:5px" class="review-link" href="/virgin-hair-reviews">VIDEO REVIEWS</a><span class="review-link">TESTIMONIALS</span>
        </div>
    </div>
    <div class="video-intro">
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('vh_testimonials_intro')->toHtml();?>
    </div>
</div>
<?php
$_reviews = Mage::getModel('review/review')
	->getResourceCollection()
	->addStoreFilter(Mage::app()->getStore()->getId())
	->addStatusFilter(Mage_Review_Model_Review::STATUS_APPROVED)
	->setDateOrder()
	->addRateVotes();
	 
foreach($_reviews as $review){
	//$product = Mage::getModel('catalog/product')->load($review->getData('entity_pk_value'));
	//echo $product->getName();
	//getTitle(), getNickname(), getDetail(), getCreatedAt()
?>	 
	<div class="the-review-item">
        <div class="the-review-detail"><?php echo $review->getDetail();?></div>
        <div class="the-reviewer">-- <?php echo $review->getNickname();;?></div>
    </div> 
<?php
	$j=0;
	$cumulative = 0;
	foreach( $review->getRatingVotes() as $vote ) { 
		$cumulative +=$vote->getPercent();
		$j++;
	}
	$finalPercentage = 0;
	if ($cumulative != 0){
		echo $finalPercentage = ($cumulative/$j);
	}
?>	
	
<?php	
}
?>

<?php //echo $this->getChildHtml('product_additional_data_review') ?>
<?php //echo $this->getChildHtml('review_form') ?>
