
<div class="sections">

<?php if($this->getItems()->getSize()){ ?>

    <?php 
    $i=0;
    foreach($this->getItems() as $_item): 
        $i++;
        $img        = $_item->getImage();
        $img_src    = str_replace('\\','/',Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $img);

        $img_mobile        = $_item->getMobileImage();
        $img_mobile_src    = str_replace('\\','/',Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $img_mobile);
        
        $link       = $_item->getLink();
		$odd_even = $i%2?'even':'odd';
		$float = $i%2?'left':'right';
    ?>

   <div class="section">
    <div class="section__wrapper">
      <div class="section__contents">
        <div class="section__image">
          <img src="<?php echo $img_src; ?>">
        </div>
        <div class="section__caption">
          <h2><?php echo $_item->getTitle();?></h2>
          <p><a href="<?php echo $link; ?>">SHOP NOW</a></p>
        </div>
      </div>
    </div>
  </div>
	
    <?php endforeach;?>

<?php } ?>

</div>
<div class="whats-new">
  <div class="whats-new__wrapper">
  	<div class="whats-new__caption">
    	<h3>Whats new</h3>
    	<a href="/shop">VIEW ALL ></a>
  	</div>
  </div>
</div>

<script>


</script>