<style>
	.page-title{
		margin-bottom:0px;
	}
	.page-title h1{
		color:#2D2B28;
		font-size:34px;
		text-align:center;
		max-width:700px;
		margin:0 auto;
	}
	.video-secrets-intro{
		color:#8A8A88;
		font-size:16px;
		text-align:center;
		max-width:700px;
		line-height:23px;
		margin:0 auto;
	}
	.the-videos > div{
		margin-left:-20px;
	}
	.the-videos > div > div.video{
		margin-top:60px;
		padding-left:20px;
		width:50%;
		box-sizing:border-box;
		text-align:center;
		float:left;
	}
	h3.video-title{
		margin:0;
	}
	h3.video-title a.video-link2{
		color:#404040;
		letter-spacing:1px;
		margin:20px auto 0px auto;
		font-size:16px;
		display:inline-block;
		max-width:400px;
	}
	div.video-description{
		color:#808285;
		font-size:14px;
		margin:0 auto;
		max-width:400px;
	}
	.the-videos{
		margin-bottom:70px;
	}
	.video .video-link, .product-video .video-link{
		background:none;
	}
	
</style>
<div class="container" style="text-align:center;margin-top:80px">
	<div class="page-title">
		<h1><?php 
    		echo $this->getLayout()->createBlock('cms/block')->setBlockId('vh_secrets_intro')->getLayout()->getBlock('head')->getTitle();
			?>
          </h1>
	</div>
    <div class="video-secrets-intro">
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('vh_secrets_intro')->toHtml();?>
    </div>
</div>
<?php
	$vhs_videos = Mage::getModel('video/video')->getCollection();
    $vhs_videos->addFieldToFilter('type_id','1');
?>
<?php if(count($vhs_videos->getItems()) > 0){ ?>
<div class="container the-videos">
	<div>
	<?php 
	$i = 0;
	foreach($vhs_videos->getItems() as $data): 
		$i++;

		$_video 	= $data->getData('video');
		$parts 		= parse_url($_video);
		$path 		= explode("/",$parts["path"]);
		$_videoId 	= array_pop($path);
		$_image 	= str_replace('\\','/',Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $data->getData('image'));
		$_title 	= $data->getData('title');
		$_desc 		= $data->getData('description');
		$_desc = 'Lorem ipsum dolor sit amet, consectetur adip Maecenas sed diam eget risus varius blandit sit amet';
		// optional can use to resize video thumbnail
		$_thumbnail = $this->helper('video/data')->resizeImg($data->getData('thumbnail'),300,360);
	?>
    	<div class="video">
        	<div>
                <div class="video-image" style="padding-top:57%;position:relative;background:#ccc">
                    <a class="video-link stretched" data-toggle="modal" data-target="#video-modal" data-video="<?php echo $_videoId;?>" style="background:url(<?php echo $_image; ?>) no-repeat center top;
                    background-size:cover">
                    </a>
                </div>
                <div class="text">
                    <h3 class="video-title">
                        <a class="video-link2" data-toggle="modal" data-target="#video-modal" data-video="<?php echo $_videoId;?>">
                            <?php echo $_title;?>
                        </a>
                    </h3>
                    <div class="video-description"><?php echo $_desc;?></div>
                </div>
            </div>
        </div>
	<?php 
		if($i==2):
			$i=0;
?>
		<div class="clearer"></div>
<?php
		endif;
		endforeach;?>
    </div>
</div>

<div class="modal fade" id="video-modal" tabindex="-1" role="dialog" aria-labelledby="video">        
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body" id="video-player">
                <div class="embed-container"><iframe src="" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>
            </div>
        </div>
        <a href="#" class="close button" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">close</span></a>
    </div>
</div>

<script>
// <![CDATA[
	// set iframe url on click
	$j('.video-link,.video-link2').on('click', function(){
	    var url 	= 'https://player.vimeo.com/video/',
	    modal 		= $j(this).data("target"),
	    videoId 	= $j(this).data("video"),
	    videoSrc 	= url+videoId, 
	    videoUrl 	= videoSrc+"?autoplay=1&amp;color=ffffff&amp;title=0&amp;byline=0&amp;portrait=0";
	    $j(modal+' iframe').attr('src', videoUrl); 
	})
	// unset url on close
	$j('#video-modal').on('hide.bs.modal', function (e) {
	    $j('#video-modal').find('iframe').attr('src', '');
	})
// ]]>
</script>

<?php } ?>